# Generated by Django 6.0.4 on 2026-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Food', 'Food'), ('Electric', 'Electric'), ('Cloth', 'Cloth')], max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product_image')),
                ('qty', models.PositiveIntegerField(null=True)),
                ('total_amount', models.FloatField(null=True)),
            ],
        ),
    ]
