# Generated by Django 6.0.4 on 2026-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_date',
            field=models.DateField(null=True),
        ),
    ]
